### ISSUE TITLE
Highlight background for same variable color is bad

### ISSUE THREAD

**Issue by nesl247** [dracula/jetbrains-legacy#1]
As you can see in the screenshot, the yellow is pretty bad when highlighting the same color. Haven't looked yet to see if that's our yellow or PhpStorm's default color.

![screen shot 2016-05-20 at 3 05 07 pm](https://cloud.githubusercontent.com/assets/1037526/15438902/63eaed9e-1e9c-11e6-95ba-2fbb5049ed2b.png)

**Comment by john-eevee** [comment]
It's a problem inherited from Darcula, the highlight is a dark yellow, I tried to modify most of them, but not all got in good matches. Do you have any idea on what color should we use?

**Comment by nesl247** [comment]
No idea what color to use. I'll probably mess around with some options later today and see.

**Comment by nesl247** [comment]
This is what I think will probably look the best.
![screen shot 2016-05-21 at 7 06 14 pm](https://cloud.githubusercontent.com/assets/1037526/15451256/3186745e-1f87-11e6-89dc-777260a623e3.png)
![screen shot 2016-05-21 at 7 06 26 pm](https://cloud.githubusercontent.com/assets/1037526/15451257/31895b6a-1f87-11e6-9d54-cf743e9e71c9.png)

This is General -> Code -> Identifier Under Caret (Write) for the setting. If you think it looks ok I'll submit a PR.

**Comment by john-eevee** [comment]
Niiice, I came up with a darker version , but the lighter is more easy to recognize through the code. The foreground we should leave unchanged, because depending on the language the parameter is a color (e.g. Java is orange)  and the error strip mark we could use the default red #FF5555.

**Comment by nesl247** [comment]
This only works if we change the foreground. Otherwise in this example, the foreground of the highlighted text in the docblock is the same color as the background. I had another version using #44475a without a foreground, but did this to make it look decent.

I didn't change the error stripe mark, that's just how it was currently.

**Comment by john-eevee** [comment]
I think #44475a will do the job, the problem with the foreground is that will change the color of the parameter if is not light blue like PHP, so the best is a background of #44475a and no foreground

**Comment by zenorocha** [comment]
That's muuuuch better ;)
