### ISSUE TITLE
Doesn’t work with WebStorm 2017.1

### ISSUE THREAD

**Issue by lukaszklis** [dracula/jetbrains-legacy#10]
Today I tried to set up the color theme in my copy of WebStorm on macOS Sierra (the latest version). After downloading the .zip file, extracting its contents, and put it in `~/Library/Preferences/WebStorm2017.1/colors` as expected, however the theme is not shown in the ”Preferences” of the IDE. It works for IntelliJ IDEA which I have installed on my machine as well.

> WebStorm 2017.1.3
> Build #WS-171.4424.63, built on May 16, 2017
> [...]
> JRE: 1.8.0_112-release-736-b21 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Mac OS X 10.12.5

**Comment by john-eevee** [comment]
Hey there!
I think Jetbrains changed the default location on Unix systems, can you try putting the `.icls`  at `~/.WebStorm2017.1/config/colors` ? We are fixing that as reported at #9

**Comment by lukaszklis** [comment]
I’ve checked it and unfortunately it doesn’t seem to work. Besides, custom-version of the default color theme was saved in `~/Library/Preferences/WebStorm2017.1/colors`. Will wait and watch the progress made in #9. Thanks anyway!

**Comment by lukaszklis** [comment]
Re-opening this since neither the new path, nor the JAR file seem to be working for WebStorm. Is there any way I can provide you more detailed info (some log files, etc.)?

**Comment by john-eevee** [comment]
I'll get a webstorm installation on my PC and see if there is anything about the webstorm

**Comment by john-eevee** [comment]
So I tried to import using both the jar and pasting the .icls file, both worked as expected. Note that I tested on the *2017.1.4* release, just the OS is different.
idk if it will work, but you can invalidate the caches for webstorm? It is located at the menu `File > Invalidate Caches \ Restart`, you need to be with an open project.

@cbracco Could you please help us with this one ?

**Comment by lukaszklis** [comment]
It still doesn’t seem to be working. :( Tried both approaches. Importing it to IntelliJ works like a charm, but WebStorm doesn’t seem to like it.

**Comment by jessemillar** [comment]
For what it's worth, I can't get things working in IntelliJ through either method.

**Comment by ghost** [comment]
@jessemillar I was able to get it to work in IntelliJ by creating the folder colors in "~/Library/Preferences/IntelliJIdea2017.1/" directly and copying the icls into that folder.

**Comment by jessemillar** [comment]
@huber-th That worked for me too. Thanks!

**Comment by swsnr** [comment]
~When I try to import `Dracula.ilcs` in IntelliJ IdeaC 2017.1 (via Preferences, Editor, Colors & Fonts, then click "Import" in the settings menu beneath the scheme dropdown), I get "Import failed: Dracula.ics is not a valid scheme".~

~When I copy into `colors` folder as suggested and restart Idea the color scheme doesn't appear in the dropdown either.~

Please disregard all of the above; an invalid settings repository broke color scheme import.  Sorry for the noise.

**Comment by john-eevee** [comment]
@lukaszklis could you try to add theme as described by @huber-th ? I never saw JB stuff behaving like that.

**Comment by john-eevee** [comment]
BTW Thanks @huber-th !!

**Comment by lukaszklis** [comment]
Okay, so I played around with the settings of WebStorm again, and the only possible way for me to add the color scheme to WebStorm was to use the built-in ”Import” option under ”Color Scheme” section in ”Settings”. Placing the `.icls` file directly into `~/Library/Preferences/WebStorm2017.2/colors` did not work.

![import-settings](https://user-images.githubusercontent.com/11782/28359146-9387f1cc-6c71-11e7-8519-f1c9f0b8b22d.jpg)
