### ISSUE TITLE
Full UI Theme?

### ISSUE THREAD

**Issue by jessemillar** [dracula/jetbrains-legacy#12]
Am I correct in thinking that making this theme encompass the entire JetBrains UI (akin to this theme: https://github.com/ChrisRM/material-theme-jetbrains) would not be a trivial task? I'm new to Dracula and JetBrains (IntelliJ IDEA specifically) but would potentially assist in theme upgrades.

**Comment by john-eevee** [comment]
Indeed it is not trivial, and currently I do not have resources to do it. 😞

**Comment by ghost** [comment]
@omgitsjoao it should be straightforward now with the support for [custom themes](https://github.com/ChrisRM/material-theme-jetbrains/tree/master/src/main/java/com/chrisrm/idea/themes)
