### ISSUE TITLE
Color Scheme incorrect in PyCharm

### ISSUE THREAD

**Issue by jasonlh-harris** [dracula/jetbrains-legacy#16]
Using PyCharms the color scheme appears to have some slight errors (See attached screenshot).  

I've imported the scheme successfully into DataGrip, which appears to have the correct colors.

![image](https://user-images.githubusercontent.com/834041/29685588-8d2b8240-88db-11e7-90a3-d1104774eb8b.png)

**Comment by john-eevee** [comment]
I'll check that up
