### ISSUE TITLE
Activation instructions incorrect for macOS

### ISSUE THREAD

**Issue by elenapalesis** [dracula/jetbrains-legacy#18]
The instructions for [installing Dracula for a JetBrains application](https://draculatheme.com/jetbrains/) contains an error in the steps for activation. It groups the activation instructions for Linux and macOS together, when in fact those instructions are only applicable to Linux systems. According to the description on this [JetBrains support page](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs), the first step in the macOS instructions should instead read:

> 1. Create a folder called `colors` inside `~/Library/Preferences/{NameOfIDE}/`.

**Comment by DanielRuf** [comment]
In my case it only worked with `~/Library/Preferences/<Product>/colors/`

**Comment by elenapalesis** [comment]
@DanielRuf you are right, that is what I meant to write! Editing my original statement to reflect this.

**Comment by john-eevee** [comment]
Thanks, and sorry for the wait.
I've submitted the changes to the site repository, you can check the [PR](https://github.com/dracula/dracula.github.io/pull/45)

**Comment by zenorocha** [comment]
This should be fixed now, sorry for the wait everyone!

**Comment by DanielRuf** [comment]
Awesome, thanks =)
