### ISSUE TITLE
Defaults: Comment tag is pink for everyone but each language has its color

### ISSUE THREAD

**Issue by john-eevee** [dracula/jetbrains-legacy#2]
![screenshot 6](https://cloud.githubusercontent.com/assets/5256711/15451370/4b5a11c0-1f95-11e6-9cb4-70ba2e810369.png)

The current color of comment tag is pink, on one hand it favors some languages but breaks others. The atom scheme for comments on Java, for example, is purple.

Even it breaks the atom compability, I think it looks great than just purple.

Here is a full sample. Any thoughts @nesl247 ?
![screenshot 7](https://cloud.githubusercontent.com/assets/5256711/15451388/f74e804c-1f95-11e6-96af-e1026268d3a4.png)

**Comment by nesl247** [comment]
I'm not following what the issue is.

**Comment by john-eevee** [comment]
The comment tag color for java and other languages on Atom is purple not pink like on PHP, but I feel it looks good pink on other languages too, so I'm asking what you think about keep the pink tag for every language or stick with Atom pattern 

Here is the Atom version
![screenshot 9](https://cloud.githubusercontent.com/assets/5256711/15451597/5dd04cd2-1fa1-11e6-8a21-ae4de5840369.png)

**Comment by nesl247** [comment]
I don't know Java, but those look like annotations, not comments, to me. The `/**...*/` block is a comment.

Edit: Looked it up to confirm and yes, they are annotations not comments. The issue in that screenshot is that `@author` isn't pink like it should be. Unless that is what you were referring to, but that isn't purple. The only purple in there is `application, sdk, constants and 22`.

**Comment by john-eevee** [comment]
Yes the first block is comments like PHP the rest are annotations, just to show is the same file as above, see the `@author` color on both images

**Comment by nesl247** [comment]
See my Edit in the comment above. The `@author` is not purple which is what was confusing me. I would agree that the docblock tag should be changed to pink. It looks a lot nicer.

**Comment by john-eevee** [comment]
Oh no problem, so let's stick with it, I really liked it!
