### ISSUE TITLE
Incorrect syntax highlighting

### ISSUE THREAD

**Issue by bl4ckb0l7** [dracula/jetbrains-legacy#20]
I'd love to use Dracula system wide, but it's broken at the moment for IntelliJ IDEA. Take a look at the same file in IDEA (left side) and VS Code (right side).

Words are highlighted incorrect and the colors differ.

![idea_vscode](https://user-images.githubusercontent.com/16593707/34895671-139c89f8-f7e7-11e7-91e7-25fd42a94e95.png)

This example is TypeScript.

**Comment by bl4ckb0l7** [comment]
In it's current state, the color scheme for Jetbrains is not useable:
![image](https://user-images.githubusercontent.com/16593707/35041732-17506950-fb86-11e7-9118-6ad5d41b2d0a.png)
Again, left Jetbrains, right VS Code.

**Comment by TreyBastian** [comment]
I agree with this. I tried this in InteliJ about 2 days ago and was sorely disappointed at the highlighting.

**Comment by john-eevee** [comment]
I agree that have some improvements to be made, but the syntax scope in IntelliJ different from VScode I would a lot less customizable, I used different colours from Classes and Interfaces thus some of them are green other blue, a part from that the invocation of methods are the other part that might be hurting, would you prefer green or white?

**Comment by maciekChmura** [comment]
Hi Guys. I've been experimenting with JavaScript. What do you think?
left - VSCode, right - Webstorm
![capture1](https://user-images.githubusercontent.com/25870428/37117741-63a51272-2252-11e8-930a-cf1f5414c5f0.PNG)

**Comment by john-eevee** [comment]
@maciekChmura feel free to PR your changes on JavaScript

**Comment by maciekChmura** [comment]
Hi Guys. I made a PR with little tweaks that work for me. Hope you will like it :)

**Comment by john-eevee** [comment]
Thanks for the PR <3! Fixed on #23
