### ISSUE TITLE
Add mention to https://github.com/mallowigi/dracula-theme-jetbrains ?

### ISSUE THREAD

**Issue by mallowigi** [dracula/jetbrains-legacy#21]
I've made a theme using the Material Theme plugin using Dracula colors and importing your color scheme. Take a look!

https://github.com/mallowigi/dracula-theme-jetbrains

**Comment by john-eevee** [comment]
Present on README, forgot to close

**Comment by mallowigi** [comment]
I wasn't talking about the Palenight theme but for the specific Dracula theme as you can see in the link here:

https://github.com/mallowigi/dracula-theme-jetbrains

**Comment by john-eevee** [comment]
Done!
