### ISSUE TITLE
Console colors for Red and Magenta are switched

### ISSUE THREAD

**Issue by iglvzx** [dracula/jetbrains-legacy#22]
I installed the Dracula theme for **IntelliJ 2018.1.5**, and I noticed that the console colors for Red and Magenta are switched. This seems counter intuitive to the color definitions as shown in the palette: https://github.com/dracula/dracula-theme#color-palette

Screenshot:

![2018-06-28_09-59-40](https://user-images.githubusercontent.com/981885/42049194-17ca1616-7aba-11e8-82e6-b9d390b11c24.png)

**Comment by iglvzx** [comment]
I looked at the history for [when console colors were added](https://github.com/dracula/jetbrains/pull/14), and I see that they are based on https://github.com/dracula/gnome-terminal , which in turn says it is based on http://ethanschoonover.com/solarized

However, even the Solarized Dark palette has intuitive Red and Magenta definitions.

So, I think it would make sense to update the console colors palette to use the correct red and magenta.

**Comment by john-eevee** [comment]
Thanks for pointing it out! If you want to submit a PR, I'll be more than happy in accept it!
