### ISSUE TITLE
Incorrect color for some keywords in IntelliJ

### ISSUE THREAD

**Issue by duffn** [dracula/jetbrains-legacy#24]
Keywords in Python do not show in the correct color.

Incorrect in JetBrains (IntelliJ 2018.2.4):
<img width="403" alt="screen shot 2018-10-03 at 9 33 06 am" src="https://user-images.githubusercontent.com/3457341/46421510-7b205500-c6ef-11e8-81fd-e53526ee2341.png">

Correct in VSCode:
<img width="415" alt="screen shot 2018-10-03 at 9 33 43 am" src="https://user-images.githubusercontent.com/3457341/46421523-807d9f80-c6ef-11e8-9ffe-d9487520f613.png">

**Comment by john-eevee** [comment]
Hi @duffn ! Can you try the theme from the branch [python-keyword](https://github.com/dracula/jetbrains/tree/python-keyword) ?

**Comment by duffn** [comment]
@sleepiejohn That branch does not exist.

**Comment by john-eevee** [comment]
Ops, forgot to mention that I merged on master, my bad, it is there now

**Comment by duffn** [comment]
The `class` keyword looks great! `True` is a slightly different color between versions, however, though this is minor.

<img width="511" alt="screen shot 2018-10-04 at 1 14 37 pm" src="https://user-images.githubusercontent.com/3457341/46497342-8a7acd80-c7d7-11e8-8ffc-053ce520c4a5.png">

**Comment by john-eevee** [comment]
this is because the way vscode maps stuff, `True` and `False` are considered Keywords on JB (correct me if I'm wrong), so we can't have different colors. If we change `True` to be purple then `class` will also be

**Comment by duffn** [comment]
Great, thanks for your feedback and help.
