### ISSUE TITLE
Are there any plans to change the Interface theme settings?

### ISSUE THREAD

**Issue by jackmoody11** [dracula/jetbrains-legacy#27]
Popular themes such as Material UI provide a fully integrated theme experience (both color theme and interface theme). I was wondering if there is any intention to do the same with the Dracula theme? Right now, the only option is to use Dracula with the default Darcula (different theme with a similar name) interface. Below is an image of the integrated theme provided by Material UI. Note how the sidebar matches the style of the code editor.

 
<img width="1440" alt="screenshot_17526" src="https://user-images.githubusercontent.com/27718962/50567920-c3fc9f80-0d18-11e9-99c4-f57f436b2063.png">

**Comment by john-eevee** [comment]
[Material Theme UI](https://plugins.jetbrains.com/plugin/8006-material-theme-ui) already ships with Dracula UI theme

**Comment by jackmoody11** [comment]
Yes, that is working as expected. I was pointing out that the part highlighted in cyan in the image below doesn't match the part in orange (which currently is the only part that matches the dracula theme).
![Dracula Sidebar](https://user-images.githubusercontent.com/27718962/51331471-1f00f700-1a7a-11e9-938c-abaa6fe685f7.png)

**Comment by gynekolog** [comment]
@jackmoody11 I try it now and theme is applied on the IDE's UI too.

![image](https://user-images.githubusercontent.com/4593089/51331752-b0706900-1a7a-11e9-87d7-daee90a62f5e.png)

**Comment by jackmoody11** [comment]
@gynekolog I didn't realize Material Theme supported Dracula. Thanks!
