### ISSUE TITLE
Error in PHPStorm 9.0.2

### ISSUE THREAD

**Issue by WinstonN** [dracula/jetbrains-legacy#4]
Getting this error on Ubuntu 14.04 PHPstorm 9.0.2 on startup

Cannot read scheme Dracula.icls from '$ROOT_CONFIG$/colors': Argument for @NotNull parameter 'element' of com/intellij/openapi/editor/markup/TextAttributes. must not be null

**Comment by john-eevee** [comment]
I'll try to reproduce on a PhpStorm on my windows, since it is cross platform, might not have issue with OS

**Comment by john-eevee** [comment]
Can you test on 2016 version of it? I tried to reproduce, but there was no problem with me.

**Comment by WinstonN** [comment]
I can confirm that this works in the latest version. I'm closing this issue, even though it does not work in 9.0.2
