### ISSUE TITLE
Instalação no Windows

### ISSUE THREAD

**Issue by murillocamargo** [dracula/jetbrains-legacy#5]
Qual o caminho para instalação no Windows?

`~/Library/Preferences/{NameOfIDE}/colors` só faz sentido no Mac.

Dei uma pesquisada e achei esse caminho para as preferências no Windows:
`<SYSTEM DRIVE>\Users\<USER ACCOUNT NAME>\.<PRODUCT><VERSION>`

Mas não achei a pasta colors.

Valeu.
Abraço.

**Comment by john-eevee** [comment]
No windows o caminho é `{Driver}\Users\{User}\.{Product}\config\colors`. Caso a pasta não exista basta cria-la.

Exemplo `C:\Users\joaoe\.IntelliJIdea2016.2\config\colors`
