### ISSUE TITLE
Gap between cursor

### ISSUE THREAD

**Issue by gabija969** [dracula/jetbrains-legacy#6]
In this halloween dracula theme for PHPStorm, there is some weird gap between cursor.

**It's not a real space just some margin or something like this. How can I fix it ? Thank you**

<img width="349" alt="screen shot 2016-11-05 at 20 32 34" src="https://cloud.githubusercontent.com/assets/22082068/20032635/05dce0ba-a397-11e6-9ce2-08dc960a4241.png">

<img width="384" alt="screen shot 2016-11-05 at 20 32 18" src="https://cloud.githubusercontent.com/assets/22082068/20032636/05dd57de-a397-11e6-9c63-14428b206f25.png">

**Comment by john-eevee** [comment]
Could be a font rendering issue, can you try with another font and see if it still happens?

**Comment by heinst** [comment]
I can second this issue

**Comment by j** [comment]
It's just a font issue.  You can fix it by sizing down the font size or choosing a new font of your choice.

**Comment by kropcik** [comment]
Yup, you are right. Changing font fixed that.

**Comment by AlexZeitler** [comment]
Changing font size fixed it for me as well. Seems to happen only with even number font sizes.

**Comment by kropcik** [comment]
halloween is gone, coming back to this issue next year lol 😆

**Comment by vikashvverma** [comment]
Had same issue, changing to odd font size fixed it...:)
