### ISSUE TITLE
Background for selected variable in the same function scope

### ISSUE THREAD

**Issue by countcain** [dracula/jetbrains-legacy#7]
<img width="938" alt="screen shot 2016-11-08 at 1 16 29 pm" src="https://cloud.githubusercontent.com/assets/1751150/20111258/a9c8971c-a5b5-11e6-83c3-6da55105959b.png">

See above image, the 4 symbols ```userObj``` will have the same background because they are in the same function scope. Through that background I can know where I use this ```userObj``` and where I declare it.

The issue is the background color is too similar to the editor background color. So it is really hard to distinguish. Do you guys know which *option* name it is and can we modify the background color value?

**Comment by john-eevee** [comment]
You can try modifying the background color at:
`Settings > Editor > Colors & Fonts > General >>> Editor > Selection background`

**Comment by countcain** [comment]
I tried. But it doesn't work. It must be another option I think.

**Comment by zenorocha** [comment]
Closing this one due to inactivity, but let me know if you have any other problems.
