### ISSUE TITLE
Update installation instructions  or Jar

### ISSUE THREAD

**Issue by jpitchardu** [dracula/jetbrains-legacy#9]
The new releases have a directory at /home like

/home/IntelliJ2017.1/config/colors/

There is where the `.icls` file goes

Also, a jar file might be useful for direct import.

**Comment by john-eevee** [comment]
Hey @pichardoJ , which OS are you using ? macOS ? if this is the new path for IntelliJ products no problem fixing that, as I already see you are doing on a fork. Since I'm running Windows my folder would be same as unix `~/.IntelliJIdea2017.2/config/colors`, a bit different than mac

**Comment by john-eevee** [comment]
Also I'll look into on how to bundle a jar to distribute it.

**Comment by jpitchardu** [comment]
I could produce a jar with IntelliJ export, I'm on Fedora, btw this is by far the best color scheme I've had in a while.

**Comment by john-eevee** [comment]
Thanks! And thanks @zenorocha  for the scheme haha.
Btw, if you want to bundle one and pull it, I'll be gladly to merge it

**Comment by jpitchardu** [comment]
@joaoevangelista Hi again, I did the PR with the exported jar.
